<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Logs</title>
    <meta name="robots" content="noindex, nofollow" />
    <link rel="stylesheet" href="/css/spectre.min.css">
    <link rel="stylesheet" href="/css/pile.css">
</head>

<body>

<div class="container">
    {% $view %}
</div>

</body>
</html>
